### PR TITLE
Paillou

### PR DESCRIPTION
**Pull request by LaurentBerger**
Implementation of Detecting step edges in noisy SAR images: a new linear operator  IEEE Transactions on Geoscience and Remote Sensing  (Volume:35 ,  Issue: 1 )  1997

### CODE REVIEW

**Comment by StevenPuttemans** [comment]
Hello Laurent, could you get an explicit confirmation of the original author Philippe Paillou that this can be integrated into OpenCV under a BSD license?

**Comment by LaurentBerger** [comment]
@StevenPuttemans I have sent an email to author. waiting for an answer.

**Comment by StevenPuttemans** [comment]
:+1:

**Comment by mshabunin** [comment]
It is better to add references to bib-file (`opencv_contrib/modules/ximgproc/doc/ximgproc.bib`) and links with doxygen `@cite paillou1997detecting`, `@cite deriche1987using` references.
```
@article{paillou1997detecting,
  title={Detecting step edges in noisy SAR images: a new linear operator},
  author={Paillou, Philippe},
  journal={IEEE transactions on geoscience and remote sensing},
  volume={35},
  number={1},
  pages={191--196},
  year={1997}
}

@article{deriche1987using,
  title={Using Canny's criteria to derive a recursively implemented optimal edge detector},
  author={Deriche, Rachid},
  journal={International journal of computer vision},
  volume={1},
  number={2},
  pages={167--187},
  year={1987},
  publisher={Springer}
}
```

**Comment by LaurentBerger** [comment]
I have got some problems with Deriche Branch and paillou Branch. I must close those branche and reopen PR

**Pull request closed without merging**
