### PR TITLE
Fixed linker error in OSX for module sfm

### PR DESCRIPTION
**Pull request by maccesch**

### CODE REVIEW

**Comment by alalek** [comment]
Please remove unnecessary merge commits.

**Comment by maccesch** [comment]
Oh, sorry. How do I do that?

**Comment by alalek** [comment]
1) `git rebase -i upstream/master` (or in your case this may work: `git rebase -i Itseez/master`).
2) Leave only 1 line with required commit (possible there is already 1 line, so nothing to edit here)
3) Save changes.
4) `git push -f origin master` to update source branch

**Comment by maccesch** [comment]
I did as you said, and it sold me that the rebase was successful. But even with `push -f` git tells me that everything is up to date.

**Comment by alalek** [comment]
It is strange, try `git rebase -i HEAD~3`

**Comment by alalek** [comment]
BTW, there is also similar thing with `GLOG_LIBRARIES`. I believe it also should be moved out of "if" and placed near `GFLAGS_LIBRARIES` fallback.

**Comment by maccesch** [comment]
You're probably right

**Comment by maccesch** [comment]
Hehe after changing that running the rebase routine again, it worked :)
Thanks

**Comment by alalek** [comment]
:+1:

**Pull request merged**
