### PR TITLE
Remove dependency on RST parser for the matlab module

### PR DESCRIPTION
**Pull request by StevenPuttemans**
Removing the dependencies with help of @berak 
should solve https://github.com/Itseez/opencv_contrib/issues/167

### CODE REVIEW

**Comment by berak** [comment]
imho, the dependancy should be removed instead, no ?

if you actually got matlab (no such thing here), do me a favour , and try [an attempt at fixing it](https://github.com/berak/opencv_contrib/tree/fix_matlab_rst)

**Comment by StevenPuttemans** [comment]
@berak yep thats true, but since I am not realy into that parsing stuff, I didn't dare to try it myself. This fix would temporarily fix it.

I will see, never built matlab bindings before, but will see where it gets me! :) Thanks!

**Comment by StevenPuttemans** [comment]
It works! I will add the changes :)

**Comment by StevenPuttemans** [comment]
@berak: I changed the python generator files, but the pyc files, how do I generate those? Because you cannot open them in an editor

**Comment by berak** [comment]
oh, nice to hear that. i originally planned to push the button myself, but you beat me to that ;)

the pyc files are locally generated, when running the py script, they should not go into the codebase at all.

**Comment by StevenPuttemans** [comment]
O great!

**Comment by StevenPuttemans** [comment]
Btw thdrksdfthmn might also be a good choice. He is quite active also!

**Comment by alalek** [comment]
:+1:

**Comment by StevenPuttemans** [comment]
thanks!

**Pull request merged**
