### PR TITLE
Graphsegmentation: First implementation

### PR DESCRIPTION
**Pull request by the-glu**
This is a proposition of an implementation of a very fast segmentation algorithm, described in [Efficient graph-based image segmentation](http://cs.brown.edu/~pff/papers/seg-ijcv.pdf).

This is my first opencv module - I hope everything is correct :)

### CODE REVIEW

**Comment by vpisarev** [comment]
thank you for the contribution! could you please put it to ximgproc instead of creating a separate module?

**Comment by cbalint13** [comment]
@the-glu , very nice work ! I am also interested getting your PR passed.

* Also could merge into single .cpp file inside /ximgproc/src ? I mean merge your actual graphsegmentation.cpp & utils.cpp . A good example how to expose things would be existing SEEDS's api (see seeds.cpp & seeds.hpp). I also follow SEEDS example/standard in my open PRs for SLIC and  LSC superpixels, so would be great if this one follows too. I would be glad to help out, feel free ping me if need help.

**Comment by the-glu** [comment]
Okay, I updated the PR with code inside ximgproc and merged everything in a single file!

Others things to fix ? :)

**Comment by vpisarev** [comment]
thank you! :+1:

**Pull request merged**
