### PR TITLE
add python bindings for Tracker and MultiTracker

### PR DESCRIPTION
**Pull request by berak**
see [#415](https://github.com/Itseez/opencv_contrib/issues/415)

also added 2 samples, tracker.py and multitracker.py

### CODE REVIEW

**Comment by berak** [comment]
@kurnianggoro , what do you think about wrapping all of it into a namespace `cv::tracking` ?

**Comment by lenlen** [comment]
@berak thank for the pull request. I'm agree with the namespace cv::tracking. I think that maybe the first step to do is merge this pending pull request (https://github.com/Itseez/opencv_contrib/pull/341/files) in which there are some important stuff for this module and then complete the python binding. What do you think?

**Comment by berak** [comment]
@lenlen , yes, so the namespace will have to wait for #341 to get merged.

should i wait with this pr, too ?

**Comment by vpisarev** [comment]
:+1:

**Pull request merged**
