### PR TITLE
Code and docs for CVPR 15' paper "DNNs are easily fooled" - with scripts to download Caffe

### PR DESCRIPTION
**Pull request by anguyen8**
Code and documentation for the CVPR '15 paper "DNNs are Easily Fooled" are placed in the modules/dnns_easily_fooled directory.

This PR is for the Vision Challenge. http://code.opencv.org/projects/opencv/wiki/VisionChallenge

@vpisarev : Hi Vadim, following https://github.com/Itseez/opencv_contrib/pull/420, I have so created scripts for users to download proper patched versions of Caffe for two different experiments in this paper. Please kindly review and let me know if anything else needs to be improved.

Best, 

Anh

### CODE REVIEW

**Comment by vpisarev** [comment]
@anguyen8, thanks! I have a couple of questions/requests regarding this PR:
1. please, correct the complains from our buildbot: pullrequest.opencv.org
2. the patch includes quite big (tough, it's smaller than caffe) external package sferes. Is it possible to document instead on how to install it separately?

**Comment by anguyen8** [comment]
@vpisarev : Thanks for your comments. I will update accordingly.

**Comment by anguyen8** [comment]
@vpisarev : Hi Vadim, I have made the requested changes:
1. The PR build-bot now passed
2. The patched Sferes is removed and instead replaced by a script for users to download it remotely. The included Installation_Guide.pdf has instructions on how to get Sferes running.

Thanks. Anh

**Comment by vpisarev** [comment]
cool! thanks! :+1:

**Pull request merged**
