### PR TITLE
ERFilter python bindings

### PR DESCRIPTION
**Pull request by lluisgomez**
first time I try to expose this code to Python. I did it by looking how other modules do it. Since ERStat is a kind of "low-level" struct with no much interest for final users I have wrapped all the process in a single function cv2.text.detectRegions() which returns a vector< vector<Point> > with all regions. (Similarly as MSER function does).

Provided sample script detect_er_chars.py works ok for me in Linux (Ubuntu 15). 

@vpisarev can you please take a look at it? thnkx!

### CODE REVIEW

**Comment by bharris47** [comment]
Would be nice to have `erGrouping` support.

**Comment by lluisgomez** [comment]
I've another PR prepared for the erGrouping python binding, but waiting for this one to be more mature (i.e. merged :)...

**Comment by Omnipresent** [comment]
@lluisgomez I am trying this PR on my local. I've copied 3 files in your commit and replaced them with the files that were there:

- (replaced) `erfilter.hpp`
- (replaced) `erfilter.cpp`
- (created new) `detect_er_chars.py`

But when I try to run `detect_er_chars.py` I get an error:

```
$ python detect_er_chars.py ~/my_pic.jpg
detect_er_chars.py
       A simple demo script using the Extremal Region Filter algorithm described in:
       Neumann L., Matas J.: Real-Time Scene Text Localization and Recognition, CVPR 2012
Traceback (most recent call last):
  File "detect_er_chars.py", line 25, in <module>
    erc1 = cv2.text.loadClassifierNM1(pathname+'/trained_classifierNM1.xml')
AttributeError: module 'cv2.text' has no attribute 'loadClassifierNM1'
```

Am I missing something? Do I need to build opencv_contrib again making these changes?

**Comment by Omnipresent** [comment]
Had to rebuild opencv (w/ opencv_contrib) and then I was able to execute `detect_er_chars`

@lluisgomez +1 to having support for `erGrouping` as @bharris47 mentioned. `erGrouping` is being used in `textdetection.cpp` sample https://github.com/Itseez/opencv_contrib/blob/master/modules/text/samples/textdetection.cpp#L65 and would be really useful to use from Python. 

Can I help in any way to get python bindings for `erGrouping` so that a sample similar to `textdetection.cpp` can be run from Python?

**Comment by vpisarev** [comment]
:+1:

**Pull request merged**
