### PR TITLE
aruco: use densely packed array for pose computation

### PR DESCRIPTION
**Pull request by paroj**
allows using Mat and vector<Vec3d> as argument for rvecs, tvecs that are
allocated at once.

### CODE REVIEW

**Comment by sergarrido** [comment]
The sample code inside the tutorials 'aruco_detection' and 'charuco_diamond_detection' should also be updated.
And I would also change the board samples (and tutorials) to use ```Vec3d``` for ```rvec``` and ```tvec```, just for consistency.

**Comment by paroj** [comment]
done

**Comment by sergarrido** [comment]
:+1:

**Comment by mshabunin** [comment]
:+1:

**Pull request merged**
