### PR TITLE
add contributions guidelines

### PR DESCRIPTION
**Pull request by StevenPuttemans**
as suggested in https://github.com/Itseez/opencv/issues/5200#issuecomment-132197315

### CODE REVIEW

**Comment by kurnianggoro** [comment]
@StevenPuttemans By any chance, do you know whether the tutorial files can be added in contrib or it have to be in main repo? I tried to put the tutorial files in contrib repo but not compiled, should I set some parameters? thanks in advance.

**Comment by StevenPuttemans** [comment]
It depends, I think, which module you are using for it.
@mshabunin should be able to give you more information!

**Comment by mshabunin** [comment]
@kurnianggoro , tutorials for contrib modules can be added to the `<module>/tutorials` subfolder, for example: https://github.com/Itseez/opencv_contrib/tree/master/modules/ximgproc/tutorials
All pages from these folders will be listed on separate documentation page: http://docs.opencv.org/master/d3/d81/tutorial_contrib_root.html#gsc.tab=0

Some additional information about tutorials and documentation writing can be found [here](http://docs.opencv.org/3.0.0/d4/db1/tutorial_documentation.html).

**Comment by kurnianggoro** [comment]
@mshabunin  thank you, turns out that I have to clean the build folder before compiling using doxygen, whenever I put the code in master I don't need to do this.

**Comment by StevenPuttemans** [comment]
@alalek done!

**Comment by alalek** [comment]
Great! :+1:

**Pull request merged**
