### PR TITLE
SurfaceMatching: OpenMP indices

### PR DESCRIPTION
**Pull request by PhilLab**
Fixes compiler error: "index variable in OpenMP 'for' statement must have signed integral type"

### CODE REVIEW

**Comment by PhilLab** [comment]
Maybe we could integrate it :-)

**Comment by bmagyar** [comment]
@vpisarev ?

**Comment by PhilLab** [comment]
Without this patch, opencv_contrib won't build under Visual Studio

**Comment by PhilLab** [comment]
@vpisarev: I believe this prevents OpenMP builds using any version of Visual Studio. The buildbot probably disables OpenMP and thus did not spot this compile-time issue. P.S.: Congrats for the 3.0 release!

**Comment by PhilLab** [comment]
@mshabunin ready to be merged - after all only a minor PR

**Comment by mshabunin** [comment]
:+1:

**Pull request merged**
