### PR TITLE
GSoC 2016: Complete DIS optical flow implementation

### PR DESCRIPTION
**Pull request by sbokov**
Added a full optimized implementation of the Dense Inverse Search (DIS) optical flow algorithm with accuracy and performance tests. Some of the older tests in the optflow module were also refactored to decrease the amount of code duplication. Here is how it currently performs in comparison to other optical-flow algorithms in OpenCV:
objective_comparison_low_res

The variational refinement part of the DIS algorithm essentially duplicates the same component of the current DeepFlow implementation, but is noticeably faster. I could replace variational refinement in DeepFlow with my implementation which would yield a significant speedup with practically no quality loss (accelerated DeepFlow on the chart above).

### CODE REVIEW

**Comment by sbokov** [comment]
Added patch mean normalization, which noticeably improves the quality on MPI-Sintel at the cost of a
very minor increase in computation time:
objective_comparison_low_res

**Comment by mshabunin** [comment]
:+1:

**Comment by maxint** [comment]
Great job!

**Comment by tikroeger** [comment]
Hey! 

I am Till Kroeger, the author of DISFlow. Currently we're on the ECCV2016 conference, where DISFlow is officially presented as conference contribution. During the discussion I was made aware that our system was already implemented in opencv_contrib. 
Great job you did there!

I would be happy if you could update the paper reference to:
T. Kroeger, R. Timofte, D. Dai, L. Van Gool, Fast Optical Flow using Dense Inverse Search, ECCV 2016.

I would also like to note that my own source code is available on my github repository since August, in case this would help in further adaptation.

Cheers,
Till

**Pull request merged**
