### PR TITLE
Fuzzy module added

### PR DESCRIPTION
**Pull request by tucna**
opencv_extra: https://github.com/Itseez/opencv_extra/pull/272

New module for image processing using fuzzy mathematics. Current version includes basic F0 operations, inpainting and filtering. Usage is tested in ***test_image*** and demonstrated in samples ***fuzzy_filtering.cpp*** and ***fuzzy_inpainting.cpp*** .

**Related papers:**

Perfilieva, Irina, and Pavel Vlašánek. "Image Reconstruction by means of F-transform." Knowledge-Based Systems 70 (2014): 55-63.

Perfilieva, Irina. "Fuzzy transforms: Theory and applications." Fuzzy sets and systems 157.8 (2006): 993-1023.

( new version and branch for the PR #224 )

### CODE REVIEW

**Comment by tucna** [comment]
@StevenPuttemans Hi Steven! This PR is here for more than one month (much more if I count also previous one with same content). Is it somehow forgottten, or should I wait longer? Thank you.

**Comment by StevenPuttemans** [comment]
@paroj it seems that core developers have been working on the testing backend for the contrib repository, and not accepting new input for the moment. I know of multiple ready to merge PRs with decent and much needed functionality. Could you maybe hold on a little bit more? Since I do not have the accepting rights for pull requests, I cannot merge PRs yet into the repository.

@vpisarev could you shed some light on why all these very decent PRs are not being handled yet?

**Comment by StevenPuttemans** [comment]
Something weird is happening. This page says the check have failed, while the buildbot said everything has passed....

**Comment by alalek** [comment]
Looks good to me (with opencv_extra patch)!
@vpisarev Please take a look.


> Something weird is happening. This page says the check have failed, while the buildbot said everything has passed....

This was failed an optional build (one of our ARM board lost network connection). I removed these results from buildbot.

**Comment by tucna** [comment]
Any news guys? I have already implemented some new features and tests, but I do not want to add them here and extend this PR.

**Comment by tucna** [comment]
@vpisarev how is it looking? I can see that some new branch conflict happened.

**Comment by alalek** [comment]
Please use "git pull --rebase upstream master" command and resolve conflict

**Comment by tucna** [comment]
@alalek, @StevenPuttemans  I can do it, but to be honest - is it worth to? I have been in this situation (for the same sources but in different PR) like 9 months ago. I fixed it, but after that something was wrong and I have to closed it and created this PR with the same content as before. And this PR is again 4 months old. 

Well, if I rebase it, what will hapen? Because if you are still not willing to merge it to the *opencv_contrib*, it makes no sense to me to do it. Because it may happen that after my rebase I will wait another 9 months with this PR and after that I can make a new rebase because of other changes.

**Comment by StevenPuttemans** [comment]
Hello @tucna, I do understand your remark completely, and I have been bringing this up with some of the core developers, since I myself have no clue why decent PR's like this one have to wait so long to get merged inside a contribute/test repository. However since I am not a core dev myself, I do not have the privilege to accept PR's.

Let us wait on the reply of @alalek or @vpisarev.

**Comment by cbalint13** [comment]
@tucna , Branch / Build issues has to be "green" and fixed otherwise maintainers cannot merge, the "merge" button simply does not appear.

**Comment by tucna** [comment]
@StevenPuttemans thank you. Well, I am going to pospone the rebase till their response.

@cbalint13 my PR was "green" for a more than half a year :) Branch conflict appeared recently because of the long merging delay.

**Comment by vpisarev** [comment]
@tucna, big thanks for the contribution! and sorry for a huge delay.
The module has been merged as https://github.com/Itseez/opencv_contrib/pull/467

**Pull request closed without merging**
