### PR TITLE
fix fc20 builds

### PR DESCRIPTION
**Pull request by volokh**
Signed-off-by: Konstantin Volokh <Konstantin.Volokh@transas.com>

### CODE REVIEW

**Comment by alalek** [comment]
:+1:

**Comment by TheodoreT** [comment]
:+1:

**Comment by dxqxiaoqiang** [comment]
hi I have trouble with this problem for many days."Module opencv_sfm disabled because the following dependencies are not found: Glog/Gflags"?I have tried many times ,but failed.Can you help me?Thanks.

**Comment by dxqxiaoqiang** [comment]
hi I have trouble with this problem for many days."Module opencv_sfm disabled because the following dependencies are not found: Glog/Gflags"?I have tried many times ,but failed.Can you help me?Thanks.
@volokh

**Comment by volokh** [comment]
Oh, I`ve just install that via:

glog-devel-0.3.3-3.fc20.x86_64
gflags-devel-1.3-8.fc20.x86_64

**Pull request merged**
