### PR TITLE
structured_light:  python / java bindings

### LINKED ISSUE #652: Java wrappers for structured_light module cannot be generated
An attempt to generate Java wrappers for the `structured_light` module by appending `WRAP java` to the `structured_light/CMakeLists.txt` file fails with the following error:
```
opencv-3.1.0/build/src/org/opencv/structured_light/GrayCodePattern.java:34: error: method create() is already defined in class GrayCodePattern
    [javac]     public static GrayCodePattern create()
    [javac]                                   ^
Linking CXX executable ../../bin/opencv_test_structured_light
    [javac] 1 error
Target 'jar' failed with message 'Compile failed; see the compiler error output for details.'.
```
Are there any guidelines on how to write OpenCV module API so that Java wrapping works well? I would like to test the module from Java.
Also, the generated Java `create` method does not have any parameters while in the C++ code the method takes one parameter: `GrayCodePattern::Params &parameters = GrayCodePattern::Params()`.

### PR DESCRIPTION
**Pull request by berak**
should fix #652

### CODE REVIEW

**Comment by berak** [comment]
warnings due to uninitialized `size_t value` will go away, once [this patch](https://github.com/Itseez/opencv/pull/6498) gets accepted.

**Comment by dharezlak** [comment]
The generated  Java API now compiles, however, when invoking `GrayCodePattern.create(1024, 768)` the following link error shows up:

```
java.lang.UnsatisfiedLinkError: org.opencv.structured_light.GrayCodePattern.create_0(II)J
	at org.opencv.structured_light.GrayCodePattern.create_0(Native Method)
	at org.opencv.structured_light.GrayCodePattern.create(GrayCodePattern.java:28)
	at pl.danhar.scan.StructuredLightTest.testStructruredLight(StructuredLightTest.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```
When looking at the native code the create method looks like this (modules/java/structured_light.cpp):
```
JNIEXPORT jlong JNICALL Java_org_opencv_structured_light_GrayCodePattern_create_10 (JNIEnv*, jclass, jint, jint);

JNIEXPORT jlong JNICALL Java_org_opencv_structured_light_GrayCodePattern_create_10
  (JNIEnv* env, jclass , jint width, jint height)
{
    static const char method_name[] = "structured_light::create_10()";
//...
```

**Comment by berak** [comment]
@dharezlak , thanks for trying, nonetheless. 

i'll reopen this, when i got a solution (and the python warnings are fixed)

**Comment by dharezlak** [comment]
Hello,

The test code is very simple for now: https://gist.github.com/dharezlak/3bed0c603d1066c59ca0be970315c171.

The build was done by using the following commands:

```
export JAVA_HOME=/usr/lib/jvm/java-8-oracle
cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=`pwd` -D BUILD_SHARED_LIBS=OFF -D OPENCV_EXTRA_MODULES_PATH=../opencv_contrib/modules ..
make -j8
```

**Comment by dharezlak** [comment]
@berak: Could you provide any pointers on what could be the problem?

**Comment by berak** [comment]
@dharezlak , unfortunately, my former dev box went up in flames (literally), and the current one does not have any java dev env, atm.

**Comment by dharezlak** [comment]
Can the problem be connected with the JNI method name resolving: https://docs.oracle.com/javase/8/docs/technotes/guides/jni/spec/design.html#resolving_native_method_names? If there is an underscore in the package name (here: `structured_light`) the native method name should contain `_1` where the underscore is present.

**Comment by dharezlak** [comment]
Yes, that seems to resolve the linking problem. After manually changing the method signatures to `Java_org_opencv_structured_1light...` in the structured_light.cpp file Java linking problem does not show again. Will report this in the original issue.

**Comment by mshabunin** [comment]
I think it is better to refactor class code a little: get rid of `Params` nested class and add several get/set methods for each property. We had similar problem with _ml_ wrappers because C++ parser and bindings generators need to be updated to understand differences between namespaces and nested classes. It seemed to be quite hard problem, so we had chosen different way - simplifying class interface (https://github.com/Itseez/opencv/pull/3679/files#diff-587e0476e652d7fcd6b954e175884346).

**Comment by dharezlak** [comment]
After @berak's modifications the `Params` class is not exposed to the Java layer at all. The only problem that was left was a proper building of the name of the package in the JNI layer which can be easily fixed by providing the fix described in https://github.com/Itseez/opencv_contrib/issues/652#issuecomment-220623626. Should we proceed with the fix?

**Comment by mshabunin** [comment]
@dharezlak , yes, lets try this fix.

**Pull request closed without merging**
