### PR TITLE
Added python aliases for face predict overloaded functions

### LINKED ISSUE #512: Predict confidence no longer accessible from Python
Recent changes to faces.hpp mean you can't call into the version of predict that returns label and confidence, you can only access the single argument version of the method.  See this thread for more details:
http://answers.opencv.org/question/82294/cant-get-predict-confidence/

### PR DESCRIPTION
**Pull request by mshabunin**
fixes #512 
Added aliases `predict_label` and `predict_collect` for python bindings.

### CODE REVIEW

**Comment by mshabunin** [comment]
:+1:

**Comment by SashaPilinovich** [comment]
Hi, i try to use PredictCollector:
`recognizer = cv2.face.createLBPHFaceRecognizer()`
`collect = cv2.face.PredictCollector()`
`recognizer.predict_collect(predict_image, collect)`
but i get an error:
`Traceback (most recent call last):`
`  File "faces.py", line 62, in <module>`
`    collect = cv2.face.PredictCollector()`
`AttributeError: 'module' object has no attribute 'PredictCollector'`
I can't figure out what I'm doing wrong? i use python 2.7, opencv 3.1.0 master branch

**Comment by mshabunin** [comment]
@SashaPilinovich , Python bindings do not have access to C++ constructors, you should call static factory method instead:
```.py
collect = cv2.face.StandardCollector_create()
```

**Comment by SashaPilinovich** [comment]
@mshabunin, thanks, now it works. If I'm not mistaken, i must use getResults, because getResultsMap not working:
`callect.getResults()`
i get some array, in this arrays i don't see pairs (pair of label and distance) and i can't  understand how to parse this array. There is some methods to work with pairs?

**Comment by mshabunin** [comment]
@SashaPilinovich , isn't it a list of tuples?
```.py
for label, distance in collect.getResults():
    print("%s -> %s" % (label, distance))
```

**Comment by SashaPilinovich** [comment]
@mshabunin, it is not work, i get an error:
`for label, distance in collect.getResults():`
`    ValueError: need more than 1 value to unpack`
if i write like this:
`for label in collect.getResults():`
`    print("%s " % (label))`
i get a lot of numbers like:
`        ...          `
`   4993497368184395691  2466071704566912598  3617879394546165289`
`    721998838099945266   722275815505136134  1662978446488506897`
`   1660149373055211562  3252759019245932824 16927315657576181829`
`        ...          `
there is no pairs

**Comment by mshabunin** [comment]
@SashaPilinovich , looks like `vector<pair<>>` return type is not correctly supported in Python bindings. Please check https://github.com/Itseez/opencv/pull/6547 , it adds required methods.

**Comment by SashaPilinovich** [comment]
@mshabunin, thanks, now it's work

**Pull request merged**
