### PR TITLE
Stereo branch

### PR DESCRIPTION
**Pull request by MMp131316**
@snosov1
Created the new stereo module with its specific files.

### CODE REVIEW

**Comment by snosov1** [comment]
That looks fine to me. Just, please, fix the warnings, so it builds ok.

@vpisarev Vadim, what about you? Also, do we want to support the C functions and structures, like CvStereoBinaryBMState?

**Comment by vpisarev** [comment]
@MMp131316, thanks for the PR! Looks good! Please, remove 
void filterSpeckles( InputOutputArray img, double newVal,
                 int maxSpeckleSize, double maxDiff,
                 InputOutputArray buf = noArray() );

Rect getValidDisparityROI( Rect roi1, Rect roi2,
			int minDisparity, int numberOfDisparities,
			int SADWindowSize );

void validateDisparity( InputOutputArray disparity, InputArray cost,
			int minDisparity, int numberOfDisparities,
			int disp12MaxDisp = 1 );

since they are present in calib3d. Also, add calib3d as dependency for the stereo module.

**Comment by MMp131316** [comment]
ok Best regards,
Muresan Mircea Paul
 


     On Tuesday, June 16, 2015 3:27 PM, Vadim Pisarevsky <notifications@github.com> wrote:
   

 @MMp131316, thanks for the PR! Looks good! Please, remove 
void filterSpeckles( InputOutputArray img, double newVal,
 int maxSpeckleSize, double maxDiff,
 InputOutputArray buf = noArray() );Rect getValidDisparityROI( Rect roi1, Rect roi2,
 int minDisparity, int numberOfDisparities,
 int SADWindowSize );void validateDisparity( InputOutputArray disparity, InputArray cost,
 int minDisparity, int numberOfDisparities,
 int disp12MaxDisp = 1 );since they are present in calib3d. Also, add calib3d as dependency for the stereo module.—

**Comment by MMp131316** [comment]
@vpisarev Hello Vadim, I have done the what you have asked

**Comment by vpisarev** [comment]
:+1:

**Pull request merged**
