### PR TITLE
GSoC 2015 Final term pull request - Structured Light project

### PR DESCRIPTION
**Pull request by RobertaRavanelli**
This is the GSoC 2015 final term pull request.

It adds the structured_ light module.

### CODE REVIEW

**Comment by vpisarev** [comment]
@RobertaRavanelli, thank you for the PR! For some reason the PR cannot be merged. Can you please look at it?

**Comment by bhack** [comment]
@vpisarev Seems that something was gone  in timeout when doing a git pull on the IOS build server.

**Comment by RobertaRavanelli** [comment]
I'm just checking now.

**Comment by vpisarev** [comment]
looks like it was connection problem with github, sorry for the false alarm

**Comment by vpisarev** [comment]
@RobertaRavanelli, @bhack, is this the final version? From my side I have no any further requests regarding the code, so I'm ready in integrate it.

**Comment by bhack** [comment]
@vpisarev It is the final version for the GSOC.

**Comment by vpisarev** [comment]
thanks! :+1:

**Comment by VictorLamoine** [comment]
Do you have datasets that you could share for testing purposes?
A set of images + calibration `yaml` files would be perfect.

Thanks for the work involved, I'm looking forward to test!

**Comment by RobertaRavanelli** [comment]
Yes, I have the datasets realized for the final GSoC video.
Let me find them and I will share them in few days.

**Comment by RobertaRavanelli** [comment]
I've added the dataset.
You can find it at: https://github.com/RobertaRavanelli/GSoC2015_statue_dataset

**Comment by VictorLamoine** [comment]
Thanks a lot, the code is working flawlessly!

**Pull request merged**
