### PR TITLE
fix errors on build samples with VS2010

### LINKED ISSUE #578: Errors on build samples with VS2010
OS WinXP x86, cmake 3.4.3, opencv ver 3.1.0-291-g695a430.

Errors on build opencv:
"Q:\ocv\opencv\build_x86_pre\OpenCV.sln" (целевой объект по умолчанию) (1) ->
"Q:\ocv\opencv\build_x86_pre\ALL_BUILD.vcxproj.metaproj" (целевой объект по умо
лчанию) (2) ->
"Q:\ocv\opencv\build_x86_pre\modules\line_descriptor\example_line_descriptor_kn
n_matching.vcxproj.metaproj" (целевой объект по умолчанию) (320) ->
"Q:\ocv\opencv\build_x86_pre\modules\line_descriptor\example_line_descriptor_kn
n_matching.vcxproj" (целевой объект по умолчанию) (321) ->
(Целевой объект ClCompile) ->
  ..\..\..\..\opencv_contrib\modules\line_descriptor\samples\knn_matching.cpp(1
14): error C2668: 'pow' : ambiguous call to overloaded function [Q:\ocv\opencv\
build_x86_pre\modules\line_descriptor\example_line_descriptor_knn_matching.vcxp
roj]

"Q:\ocv\opencv\build_x86_pre\OpenCV.sln" (целевой объект по умолчанию) (1) ->
"Q:\ocv\opencv\build_x86_pre\ALL_BUILD.vcxproj.metaproj" (целевой объект по умо
лчанию) (2) ->
"Q:\ocv\opencv\build_x86_pre\modules\optflow\example_optflow_optical_flow_evalu
ation.vcxproj.metaproj" (целевой объект по умолчанию) (354) ->
"Q:\ocv\opencv\build_x86_pre\modules\optflow\example_optflow_optical_flow_evalu
ation.vcxproj" (целевой объект по умолчанию) (355) ->
  ..\..\..\..\opencv_contrib\modules\optflow\samples\optical_flow_evaluation.cp
p(43): error C2065: 'NAN' : undeclared identifier [Q:\ocv\opencv\build_x86_pre\
modules\optflow\example_optflow_optical_flow_evaluation.vcxproj]
  ..\..\..\..\opencv_contrib\modules\optflow\samples\optical_flow_evaluation.cp
p(64): error C2065: 'NAN' : undeclared identifier [Q:\ocv\opencv\build_x86_pre\
modules\optflow\example_optflow_optical_flow_evaluation.vcxproj]

**Solution**
After replacement
`result += (uchar) ( bin_vector[i] * pow( 2, i ) );`
in opencv_contrib\modules\line_descriptor\samples\knn_matching.cpp(114) on
`result += (uchar) ( bin_vector[i] * pow( static_cast<float>(2), static_cast<int>(i) ) );`
and 
replace
`result.at<float>(i, j) = NAN;`
on
`result.at<float>(i, j) = std::numeric_limits<float>::quiet_NaN();` in
opencv_contrib\modules\optflow\samples\optical_flow_evaluation.cpp(43,64)
or define NAN
`#ifndef NAN
        static const unsigned long __nan[2] = {0xffffffff, 0x7fffffff};
        #define NAN (*(const float *) __nan)
    #endif`
the build was successful.

### PR DESCRIPTION
**Pull request by Bleach665**
fix #578 
I'm tested optical flow sample after build/ Look like everything is in order.

### CODE REVIEW

**Comment by alalek** [comment]
`pow( 2, i )` ==> `(1 << i)`
floating point introduces huge overhead here.

**Comment by alalek** [comment]
:+1:

**Comment by alalek** [comment]
Why is `signaling_NaN` used instead of `quiet_NAN()`?

**Comment by Bleach665** [comment]
I thought it would be nice to handle FPU exceptions in the future.. Back `quiet_NAN`?

**Comment by alalek** [comment]
Yes, please use `quiet_NAN`.

**Comment by alalek** [comment]
Thanks!

**Pull request merged**
