### PR TITLE
fixing facerecognizer tutorials

### PR DESCRIPTION
**Pull request by StevenPuttemans**
All the interfaces have been changed in the back but the only public documentation about it has not been adapted. Have been searching hours for the solution, lets hope that others do not have the same problem anymore.

@mshabunin could you maybe help me out with some questions? Like for example, best to use BasicFaceRecognizer or EigenFaceRecognizer and FisherFaceRecognizer?

### CODE REVIEW

**Comment by berak** [comment]
hi steven, tried your patch, and it might need some additions

* #include "opencv2/imgproc.hpp" is needed in any file, that does applyColorMap()
* LDA::subspaceProject(), not just subspaceProject() (this is also missing all over the tutorial)
* do we need 3 copies of facerecDemo.cpp (doc/src, samples, samples/src) ?
   maybe only the one in samples/src needs to be kept (and link in docs changed)

**Comment by StevenPuttemans** [comment]
@berak thanks for the remarks, well we do need the 3 samples for eigen, fisher and lbph, unless we combine everything. Will make the additions that you mentioned.

**Comment by StevenPuttemans** [comment]
Updated already every sample under the samples folder, will see what is more in that module to fix :)

**Comment by StevenPuttemans** [comment]
also, no idea why there are that many instances of the facerec demo :D

**Comment by StevenPuttemans** [comment]
Okay, seems like I have fixed every single problem in that module, tough I think some cleanup is necessary. Any guides here?

**Comment by mshabunin** [comment]
@StevenPuttemans, as I understand, BasicFaceRecognizer is an abstract class and you can not create instance of it. FisherFaceRecognizer and EigenFaceRecognizer are concrete implementations of BasicFaceRecognizer.

**Comment by StevenPuttemans** [comment]
@mshabunin well actually, as long as I did not replace the FaceRecognizer with BasicFaceRecognizer I was not able to use the new get and set functions. I guess I need to replace it by EigenFaceRecognizer and FisherFaceRecognizer Ptr?

**Comment by berak** [comment]
git diff --check     (before the commit) will highlight the pesky whitespace issues

**Comment by StevenPuttemans** [comment]
@berak indeed :D give me a minute :P

**Comment by mshabunin** [comment]
@StevenPuttemans, there are no such classes in [public API](http://docs.opencv.org/master/dc/dd7/classcv_1_1face_1_1BasicFaceRecognizer.html), so you can not use them.

**Comment by StevenPuttemans** [comment]
@mshabunin I am not sure if I get the problem.
So I can just keep the BasicFaceRecognizer for the Eigen and Fisher sample? They build just fine over here.

**Comment by mshabunin** [comment]
@StevenPuttemans , yes, you are right.

**Comment by StevenPuttemans** [comment]
:+1: made the changes and merged all the commits together

**Comment by mshabunin** [comment]
:+1:

**Comment by dshahrokhian** [comment]
This issue is happening again with OpenCV >= 3.3. The tutorials are outdated since the API has been changed once again :)

See:

- [Gender Recognition Tutorial](https://docs.opencv.org/3.0-beta/modules/face/doc/facerec/tutorial/facerec_gender_classification.html)
- [Face Recognition Tutorial](https://docs.opencv.org/3.0-beta/modules/face/doc/facerec/facerec_tutorial.html)
- [Face Recognition in Videos Tutorial](https://docs.opencv.org/3.0-beta/modules/face/doc/facerec/tutorial/facerec_video_recognition.html)

**Pull request merged**
