### PR TITLE
CNN for 3D Objects Recognition and Pose Estimation

### PR DESCRIPTION
**Pull request by Wangyida**
Part 1 of CNN for 3D Objects Recognition and Pose Estimation: Sphereview data generator
* Get view towards 3D objects, the top of the camera is always point towards the z axis.
* It will be used for Triplet training of CNN. the demo use the default sphere iteration depth of '0' and the depth could be changed in the source file.
* This is not a function yet, no parameter could be directly type in terminal.

### CODE REVIEW

**Comment by bhack** [comment]
Seems that you haven't change the module name. Choiche a module name that could rappresent your gsoc. This need to be an utility inside a module that will contain your gsoc code. Please see again the buildbot log. This PR it is failing.

**Comment by bhack** [comment]
It is a best practice to generate PR from a dedicated branch. See also the other PR in contrib.

**Comment by Wangyida** [comment]
OK, I got it, as you have said that 'Use directly a module name that represent your project and put this generator inside it as utility'. I have just create a namespace cv::sphereview3d in header files and source files, do you mean that? @bhack

**Comment by bhack** [comment]
I don't think that your gsoc module name (and folder) could be shapeview3d. Shapeview3d it is only an utility inside an opencv modules named .....?

**Comment by Wangyida** [comment]
So you mean for the module name should be my GSoC project and the module I just completed could just be represented as a class in my project's namespace, is that right? I used to think that different part in project should be placed in different places. Thanks you.

**Comment by Wangyida** [comment]
I will make a new pull request from my dedicated branch and close this PR @bhack

**Pull request closed without merging**
