### PR TITLE
Fix several bugs in aruco module

### PR DESCRIPTION
**Pull request by sergarrido**
This PR fixes several bugs in the aruco module:

- Set ```RETR_LIST``` in the ```findContours()``` function. This was an important bug that was producing many false negatives.
- Fix ```DICT_ARUCO_ORIGINAL``` error correction capacity.
- Set a better value for the parameter ```maxErroneousBitsInBorderRate```

I am preparing another PR with all the last comments/changes proposed by Prasanna.  However, I thought it was important to fix these bugs as soon as possible.

### CODE REVIEW

**Comment by paroj** [comment]
:+1:. however you should probably rebase your other PR on #384

**Comment by alalek** [comment]
#384 was merged. Are any updates expected here?

**Comment by paroj** [comment]
no - the comment was about @sergarrido's other, not yet created PR

**Comment by alalek** [comment]
:+1:

**Comment by sergarrido** [comment]
Right.
As I said, I am preparing another PR with changes proposed by Prasanna (my mentor on GSoC), but I think these bugs are important and need to be fixed as soon as possible, specially the  ```RETR_LIST``` bug.

**Pull request merged**
