### PR TITLE
Structured light stubs

### PR DESCRIPTION
**Pull request by RobertaRavanelli**
You can find the structured_light module API stubs.

### CODE REVIEW

**Comment by micuat** [comment]
Hi, I'm developing projection mapping features on the rgbd module and have some questions since eventually we want to integrate your module.

* It seems there are encoding/decoding functions, but how will be the projector/camera calibrated? We researched several methods to calibrate pro-cam, and there is a method to calibrate only with structured lighting (no checkerboard) but not stable.
* Will there be a sample code to capture projected structured light (using videoio)?

**Comment by RobertaRavanelli** [comment]
Dear Naoto,

I don't think I can help you about your first question, because the
algorithm we are implementing (3D UNDERWORLD link to download
<https://scholar.google.it/scholar?hl=it&as_sdt=0,5&q=3D+UNDERWORLD-SLS%3A+An+Open-Source+Structured-Light+Scanning+System+for+Rapid+Geometry+Acquisition>)
does not consider the projector position (it calibrates the cameras not the
projector); projector calibration was considered by the original algorithm
I wanted to implement (it is patented so I could not implement it).

As regards your second question, yes, there will be a sample code to
capture the projected structured light (it will use the libgphoto2 lib,
recently integrated in OpenCV PR link
<https://github.com/Itseez/opencv/pull/4040>).

Best regards,
Roberta

2015-06-30 17:05 GMT+02:00 Naoto HIÉDA <notifications@github.com>:

> Hi, I'm developing projection mapping features on the rgbd module and have
> some questions since eventually we want to integrate your module.
>
>    - It seems there are encoding/decoding functions, but how will be the
>    projector/camera calibrated? We researched several methods to calibrate
>    pro-cam, and there is a method to calibrate only with structured lighting
>    (no checkerboard) but not stable.
>    - Will there be a sample code to capture projected structured light
>    (using videoio)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Itseez/opencv_contrib/pull/260#issuecomment-117220079>
> .
>

-- 
___________________________________________
INVESTI SUL FUTURO, FAI CRESCERE L’UNIVERSITÀ:

*DONA IL 5 PER MILLE ALLA SAPIENZA*

CODICE FISCALE *80209930587*

**Comment by micuat** [comment]
Thanks @RobertaRavanelli for the links. Although I cannot use your algorithm directly, the gray coding feature will be helpful.

**Comment by RobertaRavanelli** [comment]
See the more recent pull request at:  [GSoC 2015 Structured Light module final PR](https://github.com/Itseez/opencv_contrib/pull/340).

**Pull request closed without merging**
