### PR TITLE
MSD Detector Added

### PR DESCRIPTION
**Pull request by m4nh**

### CODE REVIEW

**Comment by m4nh** [comment]
@StevenPuttemans @cbalint13 all seems right

**Comment by StevenPuttemans** [comment]
@m4nh it seems okay indeed. Keep in mind that for the moment the main buildbot maintainer @vpisarev is at CVPR in Boston, so probably it could take some time before he responds!

**Comment by cbalint13** [comment]
@m4nh, @StevenPuttemans, @vpisarev ,

  My modest opinion is that this PR is in very good shape, it pass all the coding conditions ! All that can be done would be "Merge", but of course lets see P.Vadim's final opinion.

Thank You Daniele, Great Job !

**Comment by yvo2m** [comment]
This code seems to be already released under the GNU GPLv3 license, it is a mainly copy of :
https://github.com/fedassa/msdDetector

**Comment by StevenPuttemans** [comment]
@yvo2m the original author agreed in the previous PR before this one that it can be merged under the currect OpenCV license.

**Comment by yvo2m** [comment]
@StevenPuttemans ok, sorry for the inconvenience. Thank you @fedassa for the contribution and Daniele for the port !

**Comment by fedassa** [comment]
thanks guys. Is the contribution ready to be merged?

**Comment by StevenPuttemans** [comment]
@fedassa I have no clue. Like I had to say to many contributors. I have the idea that developers are caught up with the GSoC students and getting their stuff in first, but this does introduce long waiting times for others.

@vpisarev 
@mshabunin 
any of you got a clue on when the contrib will merge some of the larger PRs?

**Comment by mshabunin** [comment]
@StevenPuttemans, we are trying to fix tests for contrib repository now. It is almost done, after that some PRs could be merged.

**Comment by StevenPuttemans** [comment]
:+1:

**Comment by cbalint13** [comment]
@mshabunin , by chance can this be reviewd / merged ?

**Comment by StevenPuttemans** [comment]
@cbalint13 last I heared they were trying to fix the contrib buildbots and would then start merging the bigger PRs here. But indeed ... we will loose contributions if this does not go faster, certainly with a clean PR like this one.

**Comment by mshabunin** [comment]
@m4nh, I have two comments:
- please recreate the PR from new branch with different name (not _master_ or _2.4_), our integration system could have problems testing and merging such PRs
- you've added the test but have not added the test data (accuracy and perf), so now tests are failing on buildbot. In order to make tests pass, please create additional PR to _opencv_extra_ repository with the test data (probably it will be generated automatically on first test run if it does not find needed files). The branch name should be the same as _opencv_contrib_ branch

**Comment by m4nh** [comment]
Sorry @mshabunin (and @StevenPuttemans as CC) i don't understand why to recreate PR , last PR was ok for other reviewers. However can you explain me more details about this two comments?

**Comment by StevenPuttemans** [comment]
@m4nh well, you created the PR from a branch called master on your local end. So what you do is go onto that branch and do a `git checkout -b add_msd_detector`. Now you will have a new branch with the same content but another branch name, so that buildbots do not crash.

About the second commit, even if you have tests, the tests need to get their data somewhere. therefore you need to make a PR with the data also named add_msd_detector to the opencv_extra repository, then the buildbot will find that data and everything will succeed.

Then we can finally merge your efforts!

**Comment by mshabunin** [comment]
@m4nh, the PR itself is good, problem is in branch name. OpenCV CI system checks several repositories during testing, and it automatically detects user branches to merge to mainstream before build, for example if you create pull request to _opencv_ from branch _fix-vs2015_ and pull request to _opencv_contrib_ from branch _fix-vs2015_, then they will be built and tested together: see "SourceStamps:" block on [this page](http://pullrequest.opencv.org/buildbot/builders/precommit-contrib_linux64/builds/1792). Branches _master_ and _2.4_ are blacklisted and will not be used for testing, but in your case testing should be done for _opencv_contrib_ + _opencv_extra_ which will not happen.

You need to rename the branch and create new pull request because GitHub does not allow changing branch name for created pull request. And you need to add corresponding pull request to _opencv_extra_ because new tests fail without reference testdata.

**Comment by m4nh** [comment]
@mshabunin but now i have to re-fork again opencv_contrib because they are not aligned?

**Comment by mshabunin** [comment]
@m4nh, it should be enough to create new branch from your local master as @StevenPuttemans suggested, and then push it to GitHub.

**Pull request closed without merging**
