### PR TITLE
Removed sphinx documentation

### PR DESCRIPTION
**Pull request by mshabunin**
- removed all rst-files
- reorganized tutorials and samples
- fixed some doxygen 1.8 warnings

### CODE REVIEW

**Comment by albenoit** [comment]
Wow, this is a big change.
So all sphinx doc is being deleted ? Are their any clear guidelines to move
nicely and efficiently this doc to the new recommended format?
It took some time to do it, need some time to redo it.
Thanks

2015-03-11 16:44 GMT+01:00 Maksim Shabunin <notifications@github.com>:

>
>    - removed all rst-files
>    - reorganized tutorials and samples
>    - fixed some doxygen 1.8 warnings
>
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/Itseez/opencv_contrib/pull/185
> Commit Summary
>
>    - Doxygen tutorials support
>    - Remove all sphinx files
>    - Doc files reorganized
>
> File Changes
>
>    - *D* doc/tutorials/bioinspired/retina_model/retina_model.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-0> (418)
>    - *D*
>    doc/tutorials/bioinspired/table_of_content_bioinspired/table_of_content_bioinspired.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-1> (36)
>    - *D* doc/tutorials/cvv/table_of_content_cvv/table_of_content_cvv.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-2> (37)
>    - *D*
>    doc/tutorials/cvv/visual_debugging_introduction/visual_debugging_introduction.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-3> (372)
>    - *D* doc/tutorials/ximgproc/prediction/prediction.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-4> (151)
>    - *D* doc/tutorials/ximgproc/training/training.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-5> (115)
>    - *M* modules/bgsegm/include/opencv2/bgsegm.hpp
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-6> (6)
>    - *D* modules/bioinspired/doc/bioinspired.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-7> (10)
>    - *M* modules/bioinspired/doc/retina.markdown
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-8> (57)
>    - *D* modules/bioinspired/doc/retina.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-9> (493)
>    - *A* modules/bioinspired/tutorials/images/retina_TreeHdr_retina.jpg
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-10> (0)
>    - *A* modules/bioinspired/tutorials/images/retina_TreeHdr_small.jpg
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-11> (0)
>    - *A* modules/bioinspired/tutorials/images/studentsSample_input.jpg
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-12> (0)
>    - *A* modules/bioinspired/tutorials/images/studentsSample_magno.jpg
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-13> (0)
>    - *A* modules/bioinspired/tutorials/images/studentsSample_parvo.jpg
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-14> (0)
>    - *A* modules/bioinspired/tutorials/retina_model.markdown
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-15>
>    (476)
>    - *D* modules/ccalib/doc/customPattern.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-16>
>    (202)
>    - *D* modules/cvv/doc/cvv.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-17> (11)
>    - *D* modules/cvv/doc/cvv_api.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-18> (85)
>    - *D* modules/cvv/doc/cvv_gui.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-19> (24)
>    - *A* modules/cvv/tutorials/images/01_overview_single.jpg
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-20> (0)
>    - *A* modules/cvv/tutorials/images/02_single_image_view.jpg
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-21> (0)
>    - *A* modules/cvv/tutorials/images/03_overview_two.jpg
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-22> (0)
>    - *A* modules/cvv/tutorials/images/04_default_filter_view.jpg
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-23> (0)
>    - *A* modules/cvv/tutorials/images/05_default_filter_view_high_zoom.jpg
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-24> (0)
>    - *A* modules/cvv/tutorials/images/06_default_filter_view_edges.jpg
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-25> (0)
>    - *A* modules/cvv/tutorials/images/07_dual_filter_view_edges.jpg
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-26> (0)
>    - *A* modules/cvv/tutorials/images/08_overview_all.jpg
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-27> (0)
>    - *A* modules/cvv/tutorials/images/09_overview_filtered_type_match.jpg
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-28> (0)
>    - *A* modules/cvv/tutorials/images/10_line_match_view-cutout-small.jpg
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-29> (0)
>    - *A* modules/cvv/tutorials/images/10_line_match_view-cutout.jpg
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-30> (0)
>    - *A* modules/cvv/tutorials/images/10_line_match_view.jpg
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-31> (0)
>    - *A*
>    modules/cvv/tutorials/images/11_line_match_view_portion_selector.jpg
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-32> (0)
>    - *A*
>    modules/cvv/tutorials/images/12_translation_match_view_portion_selector.jpg
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-33> (0)
>    - *A* modules/cvv/tutorials/images/13_raw_view.jpg
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-34> (0)
>    - *A* modules/cvv/tutorials/images/14_overview_group_by_line.jpg
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-35> (0)
>    - *A*
>    modules/cvv/tutorials/images/Visual_Debugging_Introduction_Tutorial_Cover.jpg
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-36> (0)
>    - *A* modules/cvv/tutorials/visual_debugging_introduction.markdown
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-37>
>    (182)
>    - *D* modules/datasets/doc/ar_hmdb.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-38> (36)
>    - *D* modules/datasets/doc/ar_sports.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-39> (18)
>    - *D* modules/datasets/doc/datasets.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-40>
>    (121)
>    - *D* modules/datasets/doc/fr_adience.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-41> (20)
>    - *D* modules/datasets/doc/fr_lfw.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-42> (31)
>    - *D* modules/datasets/doc/gr_chalearn.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-43> (22)
>    - *D* modules/datasets/doc/gr_skig.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-44> (20)
>    - *D* modules/datasets/doc/hpe_humaneva.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-45> (22)
>    - *D* modules/datasets/doc/hpe_parse.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-46> (20)
>    - *D* modules/datasets/doc/ir_affine.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-47> (20)
>    - *D* modules/datasets/doc/ir_robot.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-48> (20)
>    - *D* modules/datasets/doc/is_bsds.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-49> (20)
>    - *D* modules/datasets/doc/is_weizmann.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-50> (20)
>    - *D* modules/datasets/doc/msm_epfl.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-51> (20)
>    - *D* modules/datasets/doc/msm_middlebury.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-52> (20)
>    - *D* modules/datasets/doc/or_imagenet.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-53> (39)
>    - *D* modules/datasets/doc/or_mnist.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-54> (20)
>    - *D* modules/datasets/doc/or_sun.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-55> (22)
>    - *D* modules/datasets/doc/pd_caltech.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-56> (29)
>    - *D* modules/datasets/doc/slam_kitti.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-57> (24)
>    - *D* modules/datasets/doc/slam_tumindoor.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-58> (20)
>    - *D* modules/datasets/doc/tr_chars.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-59> (22)
>    - *D* modules/datasets/doc/tr_svt.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-60> (33)
>    - *T* modules/face/doc/etc/at.txt
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-61> (0)
>    - *D* modules/face/doc/face.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-62> (10)
>    - *D* modules/face/doc/facerec_api.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-63>
>    (412)
>    - *D* modules/face/doc/facerec_changelog.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-64> (86)
>    - *D* modules/face/doc/facerec_tutorial.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-65>
>    (628)
>    - *D* modules/face/doc/index.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-66> (31)
>    - *T* modules/face/doc/src/facerec_demo.cpp
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-67> (0)
>    - *D* modules/face/doc/tutorial/facerec_gender_classification.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-68>
>    (233)
>    - *D* modules/face/doc/tutorial/facerec_save_load.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-69> (46)
>    - *D* modules/face/doc/tutorial/facerec_video_recognition.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-70>
>    (207)
>    - *M* modules/face/include/opencv2/face.hpp
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-71> (2)
>    - *A* modules/face/samples/etc/at.txt
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-72>
>    (400)
>    - *R* modules/face/samples/src/CMakeLists.txt
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-73> (0)
>    - *R* modules/face/samples/src/create_csv.py
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-74> (0)
>    - *R* modules/face/samples/src/crop_face.py
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-75> (0)
>    - *A* modules/face/samples/src/facerec_demo.cpp
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-76>
>    (169)
>    - *R* modules/face/samples/src/facerec_eigenfaces.cpp
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-77> (0)
>    - *R* modules/face/samples/src/facerec_fisherfaces.cpp
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-78> (0)
>    - *R* modules/face/samples/src/facerec_lbph.cpp
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-79> (0)
>    - *R* modules/face/samples/src/facerec_save_load.cpp
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-80> (0)
>    - *R* modules/face/samples/src/facerec_video.cpp
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-81> (0)
>    - *R* modules/face/tutorials/face_tutorial.markdown
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-82>
>    (110)
>    - *R* modules/face/tutorials/facerec_video/facerec_video.png
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-83> (0)
>    - *R*
>    modules/face/tutorials/gender_classification/arnie_10_10_200_200.jpg
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-84> (0)
>    - *R*
>    modules/face/tutorials/gender_classification/arnie_20_20_200_200.jpg
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-85> (0)
>    - *R*
>    modules/face/tutorials/gender_classification/arnie_20_20_70_70.jpg
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-86> (0)
>    - *R*
>    modules/face/tutorials/gender_classification/arnie_30_30_200_200.jpg
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-87> (0)
>    - *R* modules/face/tutorials/gender_classification/clooney_set.png
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-88> (0)
>    - *R* modules/face/tutorials/gender_classification/fisherface_0.png
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-89> (0)
>    - *R*
>    modules/face/tutorials/gender_classification/fisherface_reconstruction_0.png
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-90> (0)
>    - *R* modules/face/tutorials/gender_classification/mean.png
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-91> (0)
>    - *R* modules/face/tutorials/img/at_database_small_sample_size.png
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-92> (0)
>    - *R* modules/face/tutorials/img/eigenface_reconstruction_opencv.png
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-93> (0)
>    - *R* modules/face/tutorials/img/eigenfaces_opencv.png
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-94> (0)
>    - *R* modules/face/tutorials/img/fisherface_reconstruction_opencv.png
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-95> (0)
>    - *R* modules/face/tutorials/img/fisherfaces_opencv.png
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-96> (0)
>    - *R* modules/face/tutorials/img/lbp/lbp.png
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-97> (0)
>    - *R* modules/face/tutorials/img/lbp/lbp_yale.jpg
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-98> (0)
>    - *R* modules/face/tutorials/img/lbp/patterns.png
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-99> (0)
>    - *D* modules/latentsvm/doc/latent_svm_cascade.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-100>
>    (113)
>    - *M* modules/latentsvm/include/opencv2/latentsvm.hpp
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-101> (4)
>    - *D* modules/line_descriptor/doc/LSDDetector.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-102>
>    (52)
>    - *D* modules/line_descriptor/doc/binary_descriptor.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-103>
>    (223)
>    - *D* modules/line_descriptor/doc/drawing_functions.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-104>
>    (70)
>    - *D* modules/line_descriptor/doc/line_descriptor.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-105>
>    (142)
>    - *D* modules/line_descriptor/doc/matching.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-106>
>    (143)
>    - *D* modules/line_descriptor/doc/tutorial.markdown
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-107>
>    (418)
>    - *D* modules/line_descriptor/doc/tutorial.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-108>
>    (428)
>    - *M* modules/line_descriptor/include/opencv2/line_descriptor.hpp
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-109> (4)
>    - *M*
>    modules/line_descriptor/include/opencv2/line_descriptor/descriptor.hpp
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-110> (4)
>    - *A* modules/line_descriptor/tutorials/tutorial.markdown
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-111>
>    (98)
>    - *D* modules/optflow/doc/dense_optflow.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-112>
>    (116)
>    - *D* modules/optflow/doc/motion_templates.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-113>
>    (125)
>    - *D* modules/optflow/doc/optflow.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-114>
>    (14)
>    - *D* modules/optflow/doc/optflow_io.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-115>
>    (36)
>    - *M* modules/optflow/include/opencv2/optflow.hpp
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-116> (2)
>    - *M* modules/optflow/include/opencv2/optflow/motempl.hpp
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-117> (2)
>    - *D* modules/reg/doc/reg.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-118> (8)
>    - *D* modules/reg/doc/registration.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-119>
>    (66)
>    - *M* modules/reg/include/opencv2/reg/map.hpp
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-120> (2)
>    - *D* modules/rgbd/doc/rgbd.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-121> (8)
>    - *D* modules/saliency/doc/common_interfaces_saliency.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-122>
>    (67)
>    - *D* modules/saliency/doc/motion_saliency_algorithms.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-123>
>    (66)
>    - *D* modules/saliency/doc/objectness_algorithms.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-124>
>    (82)
>    - *D* modules/saliency/doc/saliency.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-125>
>    (47)
>    - *D* modules/saliency/doc/saliency_categories.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-126>
>    (72)
>    - *D* modules/saliency/doc/static_saliency_algorithms.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-127>
>    (81)
>    - *R* modules/surface_matching/doc/img/gsoc_forg_matches.jpg
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-128> (0)
>    - *R* modules/surface_matching/doc/img/outline.jpg
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-129> (0)
>    - *R* modules/surface_matching/doc/img/snapshot27.jpg
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-130> (0)
>    - *D* modules/surface_matching/doc/surface_matching.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-131>
>    (355)
>    - *D*
>    modules/surface_matching/doc/surface_matching/src/ppf_load_match.cpp
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-132>
>    (146)
>    - *M* modules/surface_matching/include/opencv2/surface_matching.hpp
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-133> (8)
>    - *D* modules/text/doc/erfilter.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-134>
>    (239)
>    - *D* modules/text/doc/ocr.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-135>
>    (106)
>    - *D* modules/text/doc/text.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-136>
>    (13)
>    - *D* modules/tracking/doc/common_interfaces_tracker.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-137>
>    (290)
>    - *D* modules/tracking/doc/common_interfaces_tracker_feature_set.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-138>
>    (343)
>    - *D* modules/tracking/doc/common_interfaces_tracker_model.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-139>
>    (506)
>    - *D* modules/tracking/doc/common_interfaces_tracker_sampler.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-140>
>    (347)
>    - *A* modules/tracking/doc/diagrams.markdown
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-141>
>    (225)
>    - *D* modules/tracking/doc/tracker_algorithms.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-142>
>    (226)
>    - *D* modules/tracking/doc/tracking.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-143>
>    (63)
>    - *D* modules/tracking/doc/uml/Tracker.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-144>
>    (40)
>    - *D* modules/tracking/doc/uml/TrackerFeature.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-145>
>    (60)
>    - *D* modules/tracking/doc/uml/TrackerModel.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-146>
>    (67)
>    - *D* modules/tracking/doc/uml/TrackerSampler.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-147>
>    (45)
>    - *D* modules/tracking/doc/uml/package.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-148>
>    (15)
>    - *M* modules/tracking/include/opencv2/tracking.hpp
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-149>
>    (29)
>    - *M* modules/tracking/include/opencv2/tracking/tracker.hpp
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-150> (8)
>    - *D* modules/xfeatures2d/doc/extra_features.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-151>
>    (93)
>    - *D* modules/xfeatures2d/doc/nonfree_features.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-152>
>    (252)
>    - *D* modules/xfeatures2d/doc/xfeatures2d.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-153>
>    (11)
>    - *M* modules/xfeatures2d/include/opencv2/xfeatures2d.hpp
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-154> (4)
>    - *M* modules/xfeatures2d/include/opencv2/xfeatures2d/nonfree.hpp
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-155> (4)
>    - *D* modules/ximgproc/doc/edge_aware_filters.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-156>
>    (259)
>    - *D* modules/ximgproc/doc/structured_edge_detection.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-157>
>    (67)
>    - *D* modules/ximgproc/doc/superpixels.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-158>
>    (118)
>    - *M* modules/ximgproc/doc/ximgproc.bib
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-159> (9)
>    - *D* modules/ximgproc/doc/ximgproc.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-160>
>    (12)
>    - *M* modules/ximgproc/include/opencv2/ximgproc/edge_filter.hpp
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-161> (8)
>    - *M* modules/ximgproc/include/opencv2/ximgproc/seeds.hpp
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-162> (2)
>    - *A* modules/ximgproc/tutorials/images/01.jpg
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-163> (0)
>    - *A* modules/ximgproc/tutorials/images/02.jpg
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-164> (0)
>    - *A* modules/ximgproc/tutorials/images/03.jpg
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-165> (0)
>    - *A* modules/ximgproc/tutorials/images/04.jpg
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-166> (0)
>    - *A* modules/ximgproc/tutorials/images/05.jpg
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-167> (0)
>    - *A* modules/ximgproc/tutorials/images/06.jpg
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-168> (0)
>    - *A* modules/ximgproc/tutorials/images/07.jpg
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-169> (0)
>    - *A* modules/ximgproc/tutorials/images/08.jpg
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-170> (0)
>    - *A* modules/ximgproc/tutorials/images/09.jpg
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-171> (0)
>    - *A* modules/ximgproc/tutorials/images/10.jpg
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-172> (0)
>    - *A* modules/ximgproc/tutorials/images/11.jpg
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-173> (0)
>    - *A* modules/ximgproc/tutorials/images/12.jpg
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-174> (0)
>    - *A* modules/ximgproc/tutorials/prediction.markdown
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-175>
>    (88)
>    - *A* modules/ximgproc/tutorials/scripts/modelConvert.m
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-176>
>    (73)
>    - *A* modules/ximgproc/tutorials/training.markdown
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-177>
>    (115)
>    - *D* modules/xobjdetect/doc/integral_channel_features.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-178>
>    (236)
>    - *D* modules/xobjdetect/doc/xobjdetect.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-179>
>    (10)
>    - *M* modules/xobjdetect/include/opencv2/xobjdetect.hpp
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-180> (4)
>    - *D* modules/xphoto/doc/denoising.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-181>
>    (20)
>    - *D* modules/xphoto/doc/inpainting.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-182>
>    (20)
>    - *D* modules/xphoto/doc/whitebalance.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-183>
>    (22)
>    - *D* modules/xphoto/doc/xphoto.rst
>    <https://github.com/Itseez/opencv_contrib/pull/185/files#diff-184>
>    (10)
>
> Patch Links:
>
>    - https://github.com/Itseez/opencv_contrib/pull/185.patch
>    - https://github.com/Itseez/opencv_contrib/pull/185.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Itseez/opencv_contrib/pull/185>.
>



-- 
Alexandre BENOIT,
Associate Professor / Maître de Conférence
Image processing and visual scene classification,
LISTIC Lab / IUT Annecy
https://sites.google.com/site/benoitalexandrevision/

**Comment by mshabunin** [comment]
@albenoit, sphinx docs are not used since january. All documentation and tutorials have been converted to doxygen format already (comments in headers + `*.markdown` files). However, since the conversion was semi-automatic, there can be some issues. 
You can find nightly uploaded documentation here: http://docs.opencv.org/ref/master
Documentation writing guide is here: http://docs.opencv.org/ref/master/d4/db1/tutorial_documentation.html

**Comment by albenoit** [comment]
Ok, wow, that's really good job, i gonna check bioinspired module for
issues (if any).

thanks again and sorry for these messages.

2015-03-12 10:01 GMT+01:00 Maksim Shabunin <notifications@github.com>:

> @albenoit <https://github.com/albenoit>, sphinx docs are not used since
> january. All documentation and tutorials have been converted to doxygen
> format already (comments in headers + *.markdown files). However, since
> the conversion was semi-automatic, there can be some issues.
> You can find nightly uploaded documentation here:
> http://docs.opencv.org/ref/master
> Documentation writing guide is here:
> http://docs.opencv.org/ref/master/d4/db1/tutorial_documentation.html
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Itseez/opencv_contrib/pull/185#issuecomment-78443940>.
>



-- 
Alexandre BENOIT,
Associate Professor / Maître de Conférence
Image processing and visual scene classification,
LISTIC Lab / IUT Annecy
https://sites.google.com/site/benoitalexandrevision/

**Comment by vpisarev** [comment]
excellent! :+1:

**Pull request merged**
