### PR TITLE
Add AGAST detector

### PR DESCRIPTION
**Pull request by cbalint13**
This PR implements AGAST detector [1].

Reasons:
- AGAST is faster than FAST, and is an good alternative to have among FAST and Harris.
- AGAST has much better scoring routines, also have more testing/scoring patterns.
- Some other detector e.g. BRISK depends on it see [2] and [3] bug reports.
- Original code ported here is BSD license (compatible), and can be found at [4].
- This PR also updates test, perftest and doc, i tried to follow actual FAST implementation 1:1
- This PR has all proper citation in respect with the authors.
- This PR follows opencv of my very best try, i hope it gets accepted at all.

[1] http://www6.in.tum.de/Main/ResearchAgast
[2] http://code.opencv.org/issues/3976
[3] http://code.opencv.org/issues/2491
[4] http://sourceforge.net/projects/agastpp/

This PR rebase https://github.com/Itseez/opencv_contrib/pull/128/ (automaticaly closed due to repository vanish).

### CODE REVIEW

**Comment by vpisarev** [comment]
@cbalint13, terribly sorry for big delay; the code looks very nice. I'm basically ready to merge it in. The only request is - can you convert .rst docs to Doxygen comments? We got rid of RST in favor of Doxygen/Markdown sometime ago

**Comment by cbalint13** [comment]
@vpisarev ,
* Yes, i will fix it, allow me couple of hours, i will ping you once its done.

**Comment by cbalint13** [comment]
@vpisarev ,

- It is done, also PR rebased against upstream master.

**Comment by vpisarev** [comment]
:+1:

**Pull request merged**
