### PR TITLE
add io submodule for import scenes

### PR DESCRIPTION
**Pull request by edgarriba**
The first of a set of functions in order import scenes from different structure from motion frameworks such Bundler, VisualSfM, OpenSfM, OpenMVG and TheiSfM.

The current PR has a Bundler import function, a sample code with its correspondent tutorial

### CODE REVIEW

**Comment by alalek** [comment]
Looks good!
Could your please squash commits into one to eliminate unnecessary intermediate changes (picture added in both commits)

**Comment by alalek** [comment]
Something is going wrong during commits squash. Another commit with "CompilerFix" has been added and merged here: #484 (a5e7d8f0da2b770b8de59e342177a7caa11c970d)
```
$ git fetch upstream
$ git rebase -i upstream/master
# Edit to this and save:
# pick 0726948 add io submodule for import scenes
# f 698bfb7 fix rotation issue + small docs errors
$ git push -f origin sfm
```

Or use something like this https://github.com/Itseez/opencv_contrib/pull/290#issuecomment-145509014

**Comment by alalek** [comment]
Thank you!
:+1:

**Comment by alalek** [comment]
@edgarriba Please remove your `opencv_extra:sfm` branch

**Comment by edgarriba** [comment]
done

**Pull request merged**
