### PR TITLE
Add rotation invariance option for BRIEF descriptor.

### PR DESCRIPTION
**Pull request by cbalint13**
This is intended to be a clean patch for PR #153 done by @GilLevi . Some changes in contrast with Gil's original proposal:

  * It is against existing brief.cpp code, it is clean and well readable, in accord with opencv coding.
  * It does not fork into a new ri_brief.cpp file as original proposal, i believe this would be better.
  * It add optional flag "use_orientation" for existing brief.cpp, so users can enable the feature.
  * It pass opencv rotation invariance tests with impressive results in 16, 32, 64 byte modes.
  * By default use_orientation is disabled and it generates and behave like original BRIEF 1:1 .

.OBS:
  * It behave like L.Gil's implementation, i did some pattern compares [1] and checks in extensive ways.

[1] http://openrisc.rdsor.ro/gils-vs-opencv.png

 Apologies for PR #206 , it went wrong during squashing so i reopened a new PR here.

### CODE REVIEW

**Comment by GilLevi** [comment]
Thanks @cbalint13 , I'll add a link to your code from my blog post (with credit, of course:)

Gil

**Comment by cbalint13** [comment]
@GilLevi ,

- Not needed. I just converted your code to be lets say opencv "compliant". The 99% of work in fact is done by you from computer vision point of view, and i think it is nice one. I think would be enough to mention that your work is pending its way into opencv_contrib official repository.

**Comment by cbalint13** [comment]
@vpisarev , 

Interested in this PR ? 

* It is a very simple addition, and elegant !
* It passes very well QA, even with rised up thresholds for new rotation invariance tests.
* Evaluated on dense baseline among e.g. DAISY, it produce impressive results side-by-side.

- I am willing to further contribute with DAISY [3] (WIP) + one single very fast and nice code example/tutorial  [1] + [2] for 3D dense baseline matching. I plan use this BRIEF as alternative DAISY for dense-baseline matching in my upcoming example/tutorial.

[1] http://infoscience.epfl.ch/record/150161
[2] http://cvlab.epfl.ch/research/surface/emvs
[3] http://cvlab.epfl.ch/software/daisy

Thanks !

**Comment by cbalint13** [comment]
@vpisarev ,

* Re-Synced up with upstream so it is now "merge-able".

**Comment by vpisarev** [comment]
thanks! :+1:

**Pull request merged**
