### PR TITLE
fixed contrib code to match the HAL

### PR DESCRIPTION
**Pull request by vpisarev**
this is complimentary patch to https://github.com/Itseez/opencv/pull/3935

### CODE REVIEW

**Comment by vpisarev** [comment]
:+1:

**Comment by dhood** [comment]
I have just had to revert the hal qualifications of this commit to build the master branch of opencv_contrib (at 4d30d09b), FYI

**Comment by Dikay900** [comment]
you will need an update to date opencv source from the master branch. If you used the opencv-beta the current opencv_contrib code will not work.

With up to date opencv and opencv_contrib source it will build without any problems.
Or maybe you have some special options?

**Comment by dhood** [comment]
Yep, sorry for the noise! not sure how I missed the ref.

**Pull request merged**
