### PR TITLE
GSoC 2015 - Structured Light module

### PR DESCRIPTION
**Pull request by RobertaRavanelli**
This is the GSoC 2015 Mid Term Pull Request for the Structured Light project.

Currently with this API  it is possible to generate a Gray Code Pattern and decode an acquired pattern generating a disparity map.

### CODE REVIEW

**Comment by micuat** [comment]
FYI, I'm making a Kinect-projector calibrator using your module:
https://github.com/micuat/opencv_contrib/blob/rgbd_projection_dev/modules/rgbd/samples/sensor_projector_calibration.cpp

For the moment I changed the visibility of `getProjPixel(...)` so I can get camera-projector pixel correspondences; however, I think it will be useful to have a public function that provides a pixel correspondence map (say, returns `Mat_<Point2i> m` and an element `m.at<Point2i>(camera_x, camera_y)` returns projector xy).

**Comment by micuat** [comment]
And I noticed a huge mistake; `val1` and `val2` in `getProjPixel(...)` are opposite.

**Comment by RobertaRavanelli** [comment]
Hello Micuat,
can you explain what  you precisely mean?
Thank you.

**Comment by micuat** [comment]
Sorry about that. I just want a `public` function that returns a correspondence map something like this:
http://image.slidesharecdn.com/structuredlighting-090819173217-phpapp01/95/build-your-own-3d-scanner-3d-scanning-with-structured-lighting-6-728.jpg?cb=1250703383
The map is the camera perspective, and each pixel's value is a projector (x, y) coordinate recovered by structured light.

For the second problem, I noticed that the decoded codes' 0 and 1 are flipped.

**Comment by RobertaRavanelli** [comment]
See the more recent pull request at:  [GSoC 2015 Structured Light module final PR](https://github.com/Itseez/opencv_contrib/pull/340). With the new PR, getProjPixel() method is now public.

**Pull request closed without merging**
